# Generated by Django 2.2.13 on 2023-03-08 16:42

from django.db import migrations

def initial_data(apps, schema_editor):
    Empleado = apps.get_model('api', 'Empleado')
    Empleado.objects.create(
        codigo="A1",
        nombre="Alex",
        apellido="Veliz"
    )
    Empleado.objects.create(
        codigo="A2",
        nombre="Josué",
        apellido="Méndez"
    )
    Empleado.objects.create(
        codigo="A3",
        nombre="Alfonso",
        apellido="Lazo"
    )
    Empleado.objects.create(
        codigo="A4",
        nombre="Carlos",
        apellido="Santana"
    )

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_empleado_responsabilidad'),
    ]

    operations = [
        migrations.RunPython(initial_data)
    ]
